insert INTO currency_exchange(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1001, 'USD', 'INR', 74.54, ' ');
insert INTO currency_exchange(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1002, 'AUD', 'INR', 55.32, ' ');
insert INTO currency_exchange(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1003, 'JPY', 'INR', 00.68, ' ');
insert INTO currency_exchange(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1004, 'IDR', 'INR', 0.00515, ' ');
insert INTO currency_exchange(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (1005, 'EUR', 'INR', 88.06, ' ');